// src/screens/HomeScreenStyles.js
import { Platform, StyleSheet } from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import { COLORS, Fonts } from '../../utils/colors';
import images from '../../assets/images';
import { isTablet } from '../../components/TabletResponsiveSize';
import { rf } from '../../components/Resposive';

export default StyleSheet.create({
  safeArea: { flex: 1 },
  container: { flex: 1 },
  content: {},
  header: {
    paddingBottom: hp('1%'),
    backgroundColor: COLORS.white,
    borderBottomLeftRadius: 2,
    borderBottomRightRadius: 2,
    paddingVertical: hp('1%'),
    paddingHorizontal: wp('2.5%'),
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  addressRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginLeft: wp(0.2),
  },
  oneWidthRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: hp(2),
  },
  locationtitle: {
    fontSize: isTablet ? hp('1.6%') : hp('1.5%'),
    color: COLORS.gray,
    fontFamily: Fonts.semiBold,
    marginLeft: wp(0.5),
  },
  locationIcon: {
    width: isTablet ? wp('2%') : wp(6),
    height: isTablet ? wp('2%') : wp(6),
    alignSelf: 'flex-start',
  },
  locationText: {
    fontSize: isTablet ? hp('1.6%') : hp('1.5%'),
    color: COLORS.black,
    fontFamily: Fonts.medium,
    marginLeft: wp(0.2),
  },
  mediumText: {
    fontSize: hp('1.7%'),
    color: COLORS.black,
    fontFamily: Fonts.semiBold,
  },
  headText: {
    fontSize: hp('2%'),
    color: COLORS.black,
    fontFamily: Fonts.medium,
  },
  bigMediumText: {
    fontSize: hp('2.5%'),
    color: COLORS.black,
    fontFamily: Fonts.bold,
  },
  wheatherContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: hp('5%'),
    borderWidth: 0.5,
    borderColor: COLORS.themeColor,
    marginRight: wp('2%'),
    padding: isTablet ? hp('0.8%') : hp('0.5%'),
  },
  reqcontainer: {
    marginVertical: hp('1.5%'),
    backgroundColor: COLORS.white,
    padding: wp('2%'),
    borderRadius: wp('3%'),
    marginHorizontal: hp('1.5%'),
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  reqtitle: {
    fontSize: isTablet ? wp(2.9) : wp(3.5),
    fontFamily: Fonts.semiBold,
    color: COLORS.black,
    marginBottom: hp('1%'),
  },
  emptyCard: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    backgroundColor: 'white',
  },
  reqgrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
  },
  reqoption: {
    padding: wp('0%'),
    alignItems: 'center',
    marginVertical: hp('1%'),
    marginBottom: hp('0.5%'),
  },
  reqicon: {
    width: isTablet ? wp(11) : wp(14),
    height: isTablet ? wp(11) : wp(14),
    resizeMode: 'contain',
  },
  reqlabel: {
    fontSize: isTablet ? wp(2) : wp(3.2),
    color: COLORS.black,
    textAlign: 'center',
    marginTop: hp('1%'),
    fontFamily: Fonts.medium,
  },
  uticontainer: {
    margin: hp('1%'),
    borderRadius: wp('3%'),
    padding: wp('1%'),
    // paddingVertical: hp(3),
  },
  utigrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
    paddingTop: hp(2),
    paddingBottom: hp(2),
  },
  utititle: {
    fontSize: isTablet ? wp(2.5) : wp(3.5),
    fontFamily: Fonts.semiBold,
    color: COLORS.black,
    marginLeft: wp('2%'),
  },
  utioption: {
    paddingVertical: wp('2%'),
    width: wp('19%'),
    borderRadius: wp('2%'),
    backgroundColor: COLORS.white,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    alignItems: 'center',
    marginRight: hp('0.8%'),
  },
  utilityView: {
    paddingVertical: wp('2%'),
    maxHeight: isTablet ? hp(30) : hp(25),
    width: wp('27%'),
    borderRadius: wp('2%'),
    backgroundColor: COLORS.white,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    alignItems: 'center',
    marginRight: hp('0.8%'),
  },
  utiicon: {
    width: wp('13%'),
    height: wp('13%'),
    resizeMode: 'contain',
  },
  utilabel: {
    fontSize: wp('3%'),
    color: COLORS.black,
    fontFamily: Fonts.semiBold,
    textAlign: 'center',
    marginTop: hp('1%'),
  },
  authoption: {
    width: wp('30%'),
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: wp('1%'),
  },
  authgrid: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: wp('1.5%'),
  },
  authicon: {
    width: wp('35%'),
    height: wp('20%'),
    marginRight: 25,
    // borderWidth: 1,
    // paddingHorizontal: 20
  },
  arrowIcon: { width: wp('4.5%'), height: hp('2.5%') },
  serviceButton: {
    paddingVertical: hp('2.5%'),
    backgroundColor: COLORS.accent,
    borderRadius: 15,
    alignItems: 'center',
    marginVertical: hp('2%'),
  },
  serviceText: { fontSize: hp('1.8%'), color: COLORS.black, fontWeight: '600' },
  requestCodeContainer: {
    marginVertical: hp('2%'),
    padding: wp('3%'),
    borderRadius: 12,
  },
  requestCodeTitle: {
    fontSize: hp('2%'),
    fontWeight: '600',
    color: COLORS.black,
  },
  bookcard: {
    width: isTablet ? wp('20%') : wp('25%'),
    alignItems: 'center',
    marginVertical: hp('1%'),
  },
  bottomLine: {
    borderBottomWidth: hp('0.1%'),
    borderBottomColor: COLORS.borderColor,
    marginVertical: hp(1),
  },

  cartViewIcon: {
    backgroundColor: COLORS.themeColor,
    paddingVertical: 4,
    paddingHorizontal: 6,
    position: 'absolute',
    zIndex: 1,
    bottom: 30,
    right: 12,
    borderRadius: 7,
  },
  TotalcoutnCart: {
    backgroundColor: COLORS.white,
    paddingHorizontal: 7,
    borderRadius: 15,
    position: 'absolute',
    right: 1,
    top: -15,
    color: 'black',
    fontFamily: Fonts.bold,
    fontSize: rf(14),
  },
  productCard: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: wp('2%'),
    marginBottom: hp('0.5%'),
    width: wp('50%'),
    shadowColor: '#080808ff',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 4,
    marginHorizontal: wp('2%'),
    // marginLeft: wp('3%'),
  },
  boderinercard: {
    backgroundColor: COLORS.white,
    borderRadius: wp('3%'),
    borderColor: COLORS.borderColor,
    borderWidth: wp('0.2%'),
    // height: wp('25%'),
    paddingBottom: 10,
    marginVertical: hp('0.5%'),
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  discountBadge: {
    backgroundColor: '#ffebeb',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderTopLeftRadius: hp('1%'),
    borderBottomRightRadius: hp('1%'),
    // marginTop: hp('-2%'),
    marginRight: wp('0.8%'),
  },
  discountText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#e74c3c',
  },
  image: {
    width: '80%',
    height: '100%',
    alignSelf: 'center',
  },
  dealRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 6,
  },
  dealTag: {
    backgroundColor: '#f2f5f8',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  dealText: {
    fontSize: wp('3%'),
    color: '#6ca6d6ff',
    fontFamily: Fonts.medium,
  },
  rating: {
    fontSize: hp('1.3%'),
    fontFamily: Fonts.medium,
    color: COLORS.black,
  },
  name: {
    fontSize: hp('1.6%'),
    fontFamily: Fonts.semiBold,
    color: '#222',
    marginBottom: 4,
  },
  bottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  price: {
    fontSize: hp('1.6%'),
    fontFamily: Fonts.semiBold,
    color: COLORS.black,
  },
  mrp: {
    fontSize: hp('1.4%'),
    color: '#888',
    fontFamily: Fonts.medium,
  },
  addButton: {
    backgroundColor: COLORS.themeColor,
    // paddingHorizontal: 12,
    padding: 6,
    borderRadius: 20,
    marginVertical: hp(1),
    width: wp('35%'),
    alignSelf: 'center',
  },
  addButtonText: {
    color: '#fff',
    fontFamily: Fonts.semiBold,
    textAlign: 'center',
    fontSize: hp('1.6%'),
  },
  likeButton: {
    width: wp(3),
    height: wp(3),
    resizeMode: 'contain',
    margin: wp('1.5%'),
  },
  bottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: hp('0.5%'),
    // justifyContent: 'center',
  },

  interestText: {
    color: '#fff',
    fontFamily: Fonts.semiBold,
    textAlign: 'center',
    fontSize: hp('1.6%'),
    includeFontPadding: false, // 👈 Android text vertical fix
  },
  productView: {
    backgroundColor: COLORS.themeColor,
    borderRadius: 20,
    marginVertical: hp(1),
    width: wp('35%'),
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    height: hp('4%'),
  },
  testacard: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: wp('2%'),
    width: wp('70%'), // Adjusted for two-column layout in FlatList
    shadowColor: '#080808ff',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 4,
    marginRight: wp('3%'),
    marginLeft: wp('1%'),
  },
  testaquoteContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp('1%'),
  },
  testaquote: {
    fontSize: wp('6%'),
    color: COLORS.gray,
  },
  testimonialText: {
    fontSize: wp('2.8%'),
    color: COLORS.black,
    fontFamily: Fonts.regular,
    marginBottom: hp('1%'),
    textAlign: 'left',
  },
  testaratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  testarating: {
    fontSize: wp('3%'),
    fontFamily: Fonts.medium,
    color: COLORS.black, // Gold color for stars
  },
  testalocation: {
    fontSize: wp('3%'),
    color: COLORS.red, // Red color as per image
    fontFamily: Fonts.semiBold,
    marginBottom: hp('0.5%'),
    textAlign: 'left',
    alignSelf: 'flex-end',
  },
  testauthor: {
    fontSize: wp('3%'),
    color: COLORS.black,
    fontFamily: Fonts.medium,
    alignSelf: 'flex-end',
  },

  impcard: {
    width: wp(95),
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: wp('3.3%'),
    alignSelf: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  imptitle: {
    fontSize: wp('3.5%'),
    color: COLORS.red,
    fontFamily: Fonts.semiBold,
    textAlign: 'center',
    marginBottom: hp('2%'),
  },
  impgrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  impstatCard: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignSelf: 'center',
    width: wp('40%'),
    alignItems: 'center',
    marginBottom: hp('1%'),
    borderRadius: wp('2%'),
    borderColor: COLORS.red,
    borderWidth: wp('0.2%'),
    padding: wp('1%'),
  },
  impicon: {
    width: wp('6%'),
    height: wp('6%'),
    resizeMode: 'contain',
    marginBottom: hp('1%'),
  },
  impstatTitle: {
    fontSize: wp('2.6%'),
    color: COLORS.black,
    fontFamily: Fonts.medium,
    textAlign: 'left',
    marginBottom: hp('0.3%'),
  },
  impstatValue: {
    fontSize: wp('3%'),
    color: COLORS.black,
    fontFamily: Fonts.bold,
    textAlign: 'left',
  },

  borderSmall: {
    borderColor: COLORS.black,
    borderWidth: wp('0.2%'),
    alignSelf: 'center',
    marginVertical: hp('1%'),
    width: wp('23%'),
  },

  bannerStyle: {
    width: isTablet ? wp(95) : wp(93),
    height: isTablet ? hp(30) : hp(18),
    borderRadius: 12,
    alignSelf: 'center',
    resizeMode: 'cover',
    marginVertical: hp('2%'),
  },

  sercard: {
    width: wp(95),
    marginBottom: hp('5%'),
    alignSelf: 'center',
  },
  sertitle: {
    fontSize: wp('3.5%'),
    color: COLORS.red,
    fontFamily: Fonts.semiBold,
    textAlign: 'center',
    marginBottom: hp('2%'),
  },
  sergrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  serstatCard: {
    alignSelf: 'center',
    width: wp('22%'),
    alignItems: 'center',
    marginBottom: hp('1%'),
    padding: wp('1%'),
  },
  sericon: {
    width: wp('10%'),
    height: wp('10%'),
    resizeMode: 'contain',
    // marginBottom: hp('1%'),
  },
  serstatTitle: {
    fontSize: wp('3%'),
    color: COLORS.black,
    fontFamily: Fonts.medium,
    textAlign: 'center',
    marginBottom: hp('0.3%'),
  },

  footer: {
    paddingVertical: hp('2%'),
    alignItems: 'center',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  footerText: { fontSize: hp('1.5%'), color: COLORS.black },

  // sterilization styles
  workContain: {
    alignSelf: 'flex-start',
    height: hp('14%'),
  },
  workoption: {
    marginVertical: hp('1%'),
    paddingBottom: wp('1.5%'),
    width: wp('18%'),
    borderRadius: wp('2%'),
    backgroundColor: COLORS.black,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    alignItems: 'center',
    marginRight: hp('1.8%'),
  },
  workicon: {
    width: wp('18%'),
    height: wp('19%'),
    resizeMode: 'contain',
    borderTopLeftRadius: wp('2%'),
    borderTopRightRadius: wp('2%'),
  },
  workcontainer: { flex: 1, backgroundColor: COLORS.white },
  worksliderview: {
    marginVertical: hp('0.5%'),
    width: wp('100%'),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  workimage: {
    width: isTablet ? wp(95) : wp(95),
    height: isTablet ? wp(40) : wp(40),
    resizeMode: 'contain',
  },
  workscrollstyle: { flex: 1, paddingHorizontal: wp('3%') },
  workheadText: {
    fontSize: isTablet ? wp(2.8) : wp(4),
    fontFamily: Fonts.semiBold,
    marginBottom: hp('1%'),
    color: COLORS.black,
  },
  workitem: {
    justifyContent: 'space-between',
    padding: hp('1%'),
    backgroundColor: '#fff',
    marginBottom: hp('1.5%'),
    borderRadius: 10,
  },
  worktext: {
    fontSize: hp('1.6%'),
    color: COLORS.black,
    fontFamily: Fonts.medium,
  },
  workacIconstyle: {
    width: wp('7%'),
    height: hp('5%'),
    marginRight: wp('3.5%'),
    resizeMode: 'contain',
  },
  workbuttonContainer: { flexDirection: 'row', alignItems: 'center' },
  workbutton: {
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: hp('5%'),
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 5,
    width: isTablet ? wp(6) : wp(7.3),
    height: isTablet ? wp(6) : wp(7.3),
    alignSelf: 'center',
  },
  workbuttonText: {
    fontSize: isTablet ? wp(3) : wp(5),
    color: COLORS.black,
    textAlignVertical: 'top',
    fontFamily: Fonts.medium,
    marginBottom: Platform.OS === 'ios' ? hp('0.5%') : wp('2%'),
    position: 'absolute',
  },
  workcount: {
    marginHorizontal: 4,
    color: COLORS.themeColor,
    textAlign: 'center',
    fontFamily: Fonts.medium,
    fontSize: isTablet ? hp(1.5) : hp('1.3%'),
  },
  workaddButton: {
    borderColor: COLORS.darkGray,
    borderWidth: wp('0.3%'),
    borderRadius: wp('7%'),
    width: wp('18%'),
    height: hp('3.5%'),
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  workaddButtonText: {
    fontSize: wp('3%'),
    color: COLORS.black,
    fontFamily: Fonts.medium,
  },
  serviceCartButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: wp('0%'),
    paddingHorizontal: hp('1%'),
    backgroundColor: COLORS.themeColor,
    borderRadius: wp(2),
    width: wp(43),
  },
  boderwhiteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: wp('0%'),
    paddingHorizontal: hp('1%'),
    backgroundColor: COLORS.themeColor,
    borderRadius: wp(2),
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.TextColor,
  },

  // FAQ STYLE
  faqItem: {
    marginTop: wp('1%'),
    backgroundColor: COLORS.white,
    borderRadius: wp('3%'),
    marginBottom: hp('0.6%'),
    overflow: 'hidden', // To clip content within border radius
  },
  faquestionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
  },
  faquestionText: {
    fontSize: isTablet ? hp('1.7%') : hp('1.6%'),
    color: COLORS.black,
    fontFamily: Fonts.semiBold,
    marginVertical: wp('2%'),
  },
  faqarrow: {
    alignSelf: 'center',
    fontSize: 18,
    color: COLORS.darkText,
  },
  faqanswerText: {
    fontSize: isTablet ? hp(1.5) : hp(1.5),
    fontFamily: Fonts.medium,
    color: COLORS.textHeading,
    paddingHorizontal: isTablet ? wp(1.5) : wp('3%'),
    paddingBottom: wp('3%'),
    lineHeight: 20,
  },
  brandimage: {
    width: isTablet ? wp(95) : wp(95),
    height: isTablet ? wp(15) : wp(15),
    resizeMode: 'contain',
  },
  smallimage: {
    width: wp('10%'),
    height: hp('6%'),
    resizeMode: 'contain',
  },
  brandcont: {
    backgroundColor: COLORS.white,
    borderRadius: wp('3%'),
    marginBottom: hp('18%'),
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp('3%'),
    justifyContent: 'space-between',
    marginTop: hp(1),
    paddingVertical: isTablet ? wp(1.5) : wp(1.5),
  },
  needHelp: {
    fontSize: wp('3.7%'),
    color: COLORS.textHeading,
    fontFamily: Fonts.semiBold,
    marginLeft: wp('4%'),
  },
  chaticon: {
    width: wp('20%'),
    height: hp('4.5%'),
    resizeMode: 'contain',
  },
  servicesSection: {
    width: '100%',
    paddingHorizontal: wp(4),
    paddingVertical: hp(2),
    paddingBottom: hp(3),
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: COLORS.white,
  },
  servicesCount: {
    fontSize: isTablet ? wp(2.5) : wp('3.5%'),
    fontFamily: Fonts.semiBold,
    color: COLORS.darkText,
  },
  selectedText: {
    fontSize: wp('3%'),
    fontFamily: Fonts.semiBold,
    color: COLORS.darkText,
    opacity: 0.7,
  },
  viewCartButton: {
    flexDirection: 'row',
    alignItems: 'center',
    // paddingVertical: wp('0%'),
    paddingVertical: wp(1),
    paddingHorizontal: wp('3%'),
    backgroundColor: COLORS.themeColor,
    borderRadius: wp(10),
  },
  viewCartText: {
    fontSize: isTablet ? wp(2.5) : wp('3%'),
    fontFamily: Fonts.semiBold,
    color: COLORS.white,
    marginRight: 4,
  },

  carticon: {
    width: wp('4%'),
    height: wp('4%'),
    resizeMode: 'contain',
  },
  // Btn View
  BtnView: {
    width: '100%',
    paddingHorizontal: wp(4),
    paddingVertical: hp(3),
    backgroundColor: COLORS.white,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    elevation: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },

  // account styles
  accountbg: {
    width: isTablet ? wp(16) : wp(20),
    height: isTablet ? wp(16) : wp(20),
    resizeMode: 'cover',
    borderRadius: wp('2%'),
    marginLeft: wp('1%'),
  },
  accounttitle: {
    fontSize: hp('1.8%'),
    color: COLORS.black,
    fontFamily: Fonts.semiBold,
  },
  accountNumber: {
    fontSize: hp('1.5%'),
    color: COLORS.textColor,
    fontFamily: Fonts.medium,
    marginLeft: wp('1%'),
  },
  accountline: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: hp('0.5%'),
    marginBottom: wp('1%'),
  },
  accountbgcontainer: {
    marginBottom: hp('0.5%'),
    backgroundColor: COLORS.white,
    borderRadius: wp('2%'),
    marginHorizontal: hp('0.5%'),
  },
  accountinfocontainer: {
    marginBottom: hp('1%'),
    backgroundColor: COLORS.white,
    marginHorizontal: hp('0.5%'),
  },
  accountMaincontainer: {
    marginVertical: hp('1%'),
    backgroundColor: COLORS.white,
    borderRadius: wp('2%'),
    marginHorizontal: hp('1.5%'),
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: hp('1%'),
  },
  accountcontainer: {
    backgroundColor: COLORS.white,
    marginHorizontal: hp('0.5%'),
  },
  callIcon: {
    width: wp('4%'),
    height: hp('3%'),
    alignSelf: 'flex-start',
  },
  acccontainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingVertical: hp(1.3),
    marginBottom: hp(1),
    paddingHorizontal: wp(4),
    borderRadius: wp(3),
    marginVertical: hp(0.5),
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  acciconContainer: {
    width: wp(10),
    alignItems: 'center',
  },
  accicon: {
    width: wp(7),
    height: wp(7),
    resizeMode: 'contain',
  },
  acctitle: {
    flex: 1,
    fontSize: hp(1.5),
    color: COLORS.textHeading,
    marginLeft: wp(3),
    fontFamily: Fonts.medium,
  },
  accarrow: {
    width: wp(4),
    height: wp(4),
    tintColor: '#444343ff',
  },
  accountBlueText: {
    fontSize: hp('2%'),
    color: COLORS.themeColor,
    fontFamily: Fonts.semiBold,
  },
  //  profile details styles end
  profilestyle: {
    width: isTablet ? wp(18) : wp(25),
    height: isTablet ? wp(18) : wp(25),
    resizeMode: 'contain',
    borderRadius: hp('2%'),
  },
  profileDetailBg: {
    width: isTablet ? wp(18) : wp(25),
    height: isTablet ? wp(18) : wp(25),
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: hp(5),
    marginBottom: hp('2%'),
  },
  cameraStyle: {
    width: isTablet ? wp(10) : wp(12),
    height: isTablet ? wp(10) : wp(12),
    resizeMode: 'contain',
    position: 'absolute',
    left: isTablet ? wp(12) : wp(18),
    top: isTablet ? wp(14) : wp(18),
  },
  profileDetailInput: {
    borderWidth: 1,
    borderColor: COLORS.borderColor,
    borderRadius: wp('6%'),
    paddingHorizontal: wp('3%'),
    paddingVertical: hp('1.5%'),
    fontSize: hp('1.6%'),
    color: COLORS.black,
    fontFamily: Fonts.medium,
    marginVertical: hp('1.5%'),
    backgroundColor: COLORS.white,
  },
  profileDetailName: {
    fontSize: hp('1.5%'),
    color: COLORS.black,
    fontFamily: Fonts.medium,
    marginTop: hp('1%'),
  },
  allSideRadiusStyle: {
    width: wp('95%'),
    alignSelf: 'center',
    marginTop: hp('1%'),
    paddingBottom: hp('1%'),
    backgroundColor: COLORS.white,
    borderRadius: wp(3),
    paddingVertical: hp('1%'),
    paddingHorizontal: wp('2.5%'),
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
});

export const productData = [
  {
    id: '1',
    name: 'Godrej 1.5 Ton 3 Star Inverter Split AC',
    price: '₹ 41,990',
    mrp: '₹ 65,990',
    discount: '36% off',
    rating: '4.3',
    reviews: 'Limited time deal',
    image: images.ACimage, // Adjust path
  },
  {
    id: '2',
    name: 'LG 1.5 Ton 5 Star AI Dual Inverter Split AC',
    price: '₹ 47,490',
    mrp: '₹ 72,990',
    discount: '35% off',
    rating: '4.5',
    reviews: 'Limited time deal',
    image: images.ACimage, // Adjust path
  },
  {
    id: '3',
    name: 'Daikin 1 Ton 3 Star Inverter Split AC',
    price: '₹ 32,999',
    mrp: '₹ 50,000',
    discount: '34% off',
    rating: '4.2',
    reviews: 'Limited time deal',
    image: images.ACimage, // Adjust path
  },
  {
    id: '4',
    name: 'Hitachi 1.5 Ton 5 Star Inverter Split AC',
    price: '₹ 48,499',
    mrp: '₹ 75,000',
    discount: '35% off',
    rating: '4.4',
    reviews: 'Limited time deal',
    image: images.ACimage, // Adjust path
  },
  {
    id: '5',
    name: 'Samsung 1 Ton 3 Star Inverter Split AC',
    price: '₹ 30,990',
    mrp: '₹ 46,990',
    discount: '34% off',
    rating: '4.1',
    reviews: 'Limited time deal',
    image: images.ACimage, // Adjust path
  },
];

export const testimonialData = [
  {
    id: '1',
    text: 'It has been a great pleasure working with AC Doctor. The know-how of their technical team is way beyond perfection and quality. We wish them all the very best for the future.',
    rating: '4.7',
    location: 'Mahidpurwala, Indore',
    author: 'Adnan Raja (Director)',
  },
  {
    id: '2',
    text: 'Excellent service by AC Doctor! Their team is highly skilled and professional. Highly recommend them!',
    rating: '4.6',
    location: 'Vijay Nagar, Indore',
    author: 'Priya Sharma (Manager)',
  },
  {
    id: '3',
    text: 'Amazing experience with AC Doctor. Quick response and top-notch quality work!',
    rating: '4.8',
    location: 'Scheme No. 54, Indore',
    author: 'Rakesh Patel (Owner)',
  },
  {
    id: '4',
    text: 'The best AC service I’ve ever had. Their team is knowledgeable and efficient.',
    rating: '4.5',
    location: 'South Tukoganj, Indore',
    author: 'Sunil Mehta (Engineer)',
  },
  {
    id: '5',
    text: 'AC Doctor exceeded my expectations with their service and expertise. Great job!',
    rating: '4.7',
    location: 'Bhawarkua, Indore',
    author: 'Anita Desai (Customer)',
  },
];

export const works = [
  {
    id: '1',
    text: 'Ac repair',
    icon: images.demoImgOne,
  },
  {
    id: '2',
    text: 'Split AC',
    icon: images.demoImgTwo,
  },
  {
    id: '3',
    text: 'Window AC',
    icon: images.demoImgthree,
  },
  {
    id: '4',
    text: 'Tower AC',
    icon: images.demoImg,
  },
  {
    id: '5',
    text: 'Ducted AC',
    icon: images.demoImgOne,
  },
];

// Data arrays passed as props
export const keyBenefitsData = [
  {
    title: 'Enhanced Cooling Efficiency',
    desc: 'Ensures optimal performance, reducing cooling time and electricity consumption.',
  },
  {
    title: 'Extended AC Lifespan',
    desc: 'Regular maintenance prevents breakdowns and prolongs the life of your AC unit.',
  },
  {
    title: 'Improved Air Quality',
    desc: 'Removes dirt, dust, and bacteria buildup, ensuring cleaner and healthier air circulation.',
  },
  {
    title: 'Prevents Costly Repairs',
    desc: 'Early detection of issues helps avoid major repair costs in the future.',
  },
  {
    title: 'Consistent Performance',
    desc: 'Keeps the AC running smoothly, avoiding sudden failures during peak summer months.',
  },
];

export const serviceInclusionsData = [
  {
    title: 'Service Inclusions',
    items: [
      'Thorough inspection and diagnosis of the compressor.',
      'Refrigerant level check and top-up (additional cost if required).',
      'Lubrication of moving parts for smooth operation.',
      'Testing for gas leaks and fixing minor leaks if found.',
      'Cleaning of compressor components to remove dust and debris.',
    ],
  },
  {
    title: 'Service Exclusions',
    items: [
      'Major repairs or part replacements are not included in basic service.',
      'Gas refilling is chargeable if needed.',
    ],
  },
];

export const termsConditionsData = [
  {
    text: "Service time may vary based on the AC's condition and number of units.",
  },
  {
    text: 'If additional repairs are required, a separate quotation will be provided.',
  },
  { text: 'Warranty on service is valid for 15 days post-servicing.' },
  {
    text: 'Customers must ensure accessibility to the AC unit before service begins.',
  },
  {
    text: 'Service is canceled after booking, a nominal cancellation charge may apply.',
  },
];

export const faqData = [
  {
    question: 'Why is my AC not cooling properly?',
    answer:
      'This can happen due to dirty filters, low gas, blocked coils, thermostat issues, poor outdoor ventilation, or internal faults. Regular servicing helps fix these issues.',
  },
  {
    question: 'How often should I service my AC?',
    answer:
      'Home ACs need servicing every 3–6 months. Commercial ACs every 2–3 months. Always service before summer.',
  },
  {
    question: 'Does regular AC servicing reduce \n electricity bills?',
    answer:
      'Yes. A well-maintained AC uses less power and cools faster, helping reduce electricity costs.',
  },
  {
    question: 'When should I book AC servicing?',
    answer:
      'Book servicing before peak summer or whenever cooling performance drops.',
  },
];

export const WindoData = [
  {
    question: 'Manufacture Details',
    title: 'Brand',
    text: 'Voltas',
    capacity: '2 Tons',
    cooling: '3200 Watts',
    feature: 'Antibacterial coaring',
    colour: 'White',
    voltage: '230 volts',
    product: ` 84D x 84D x 23H 
              Centimeters`,
    noise: '44 dB',
    floor: '180 Square Feet',
    power: 'Corded Electric',
  },
  {
    question: 'Manufacture Details',
    title: 'Brand',
    text: 'Voltas',
    capacity: '2 Tons',
    cooling: '3200 Watts',
    feature: 'Antibacterial coaring',
    colour: 'White',
    voltage: '230 volts',
    product: ` 84D x 84D x 23H 
              Centimeters`,
    noise: '44 dB',
    floor: '180 Square Feet',
    power: 'Corded Electric',
  },
  {
    question: 'Manufacture Details',
    title: 'Brand',
    text: 'Voltas',
    capacity: '2 Tons',
    cooling: '3200 Watts',
    feature: 'Antibacterial coaring',
    colour: 'White',
    voltage: '230 volts',
    product: ` 84D x 84D x 23H 
              Centimeters`,
    noise: '44 dB',
    floor: '180 Square Feet',
    power: 'Corded Electric',
  },
  {
    question: 'Manufacture Details',
    title: 'Brand',
    text: 'Voltas',
    capacity: '2 Tons',
    cooling: '3200 Watts',
    feature: 'Antibacterial coaring',
    colour: 'White',
    voltage: '230 volts',
    product: ` 84D x 84D x 23H 
              Centimeters`,
    noise: '44 dB',
    floor: '180 Square Feet',
    power: 'Corded Electric',
  },
];

export const CompareData = [
  {
    question: 'Manufacture Details',
    title: 'Brand',
    secondTitle: 'Model Series',
    Thirdtitle: 'Model Number',
  },
  {
    question: 'Product Dimensions(Open)',
    title: 'Brand',
    secondTitle: 'Model Series',
    Thirdtitle: 'Model Number',
  },
  {
    question: 'Air Conditioner Features',
    title: 'Brand',
    secondTitle: 'Model Series',
    Thirdtitle: 'Model Number',
  },
  {
    question: 'Air Conditioner Functions',
    title: 'Brand',
    secondTitle: 'Model Series',
    Thirdtitle: 'Model Number',
  },
  {
    question: 'Air Conditioner Physical Attributes',
    title: 'Brand',
    secondTitle: 'Model Series',
    Thirdtitle: 'Model Number',
  },
  {
    question: 'Air Conditioner Screen Specification',
    title: 'Brand',
    secondTitle: 'Model Series',
    Thirdtitle: 'Model Number',
  },
  {
    question: 'Remote Control Details',
    title: 'Brand',
    secondTitle: 'Model Series',
    Thirdtitle: 'Model Number',
  },
  {
    question: 'Air Conditioner PIUG Details',
    title: 'Brand',
    secondTitle: 'Model Series',
    Thirdtitle: 'Model Number',
  },
  {
    question: 'Air Conditioner Functions',
    title: 'Brand',
    secondTitle: 'Model Series',
    Thirdtitle: 'Model Number',
  },
];

export const menuData = [
  {
    id: '1',
    title: 'Notification',
    icon: images.notificationRed,
    screen: 'NotificationScreeen',
  },
  {
    id: '2',
    title: 'My Bookings',
    icon: images.bookingIcon,
    screen: 'MyBookingScreen',
  },
  {
    id: '3',
    title: 'My Requests',
    icon: images.bookingIcon,
    screen: 'MyRequestsScreen',
  },
  {
    id: '4',
    title: 'Manage Address',
    icon: images.addressIcon,
    screen: 'ManageAddressScreen',
  },
  {
    id: '5',
    title: 'Annual Maintenance Contract',
    icon: images.contractIcon,
    screen: 'AMC',
  },
  { id: '6', title: 'Pay Now', icon: images.payIcon, screen: 'PayNow' },
  { id: '7', title: 'Rate Us', icon: images.rateUSIcon, screen: 'RateUs' },
  { id: '8', title: 'Help', icon: images.helpIcon, screen: 'Help' },
  { id: '9', title: 'Logout', icon: images.logoutIcon, screen: 'Logout' },
];
